// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*DFMFileType*/ /*C\CRESD\SOURCE\GAKLIB\REPOSITORY\StatusFrm.dfm*/
/*ITE*/ /*DFMFileType*/ /*srxViewerFrm.dfm*/
/*ITE*/ /*DFMFileType*/ /*vcl\DBLOGDLG.dfm*/
/*ITE*/ /*DFMFileType*/ /*vcl\DBPWDLG.dfm*/
/*ITE*/ /*RCFileType*/ /*..\..\OBJECT\srxViewer_DRC.rc*/
//---------------------------------------------------------------------------
USEFORMRES("C\CRESD\SOURCE\GAKLIB\REPOSITORY\StatusFrm.dfm", StatusForm, Form); /* TForm: DesignClass */
USEFORMRES("srxViewerFrm.dfm", srxViewerForm, Form); /* TForm: DesignClass */
USEFORMRES("vcl\DBLOGDLG.dfm", LoginDialog, Form); /* Form: DesignClass */
USEFORMRES("vcl\DBPWDLG.dfm", PasswordDialog, Form); /* Form: DesignClass */
USERC("..\..\OBJECT\srxViewer_DRC.rc");
USERES("srxViewer.res");
//---------------------------------------------------------------------------
#define DllEntryPoint
